name: well_navigate
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  code_text_field: ^1.1.0
  cupertino_icons: ^1.0.6
  fhir_client: 
    path: ../
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.18

dev_dependencies:
  austerity: ^1.2.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf