
include: package:austerity/analysis_options.yaml

analyzer:
  errors:
    unrelated_type_equality_checks: warning
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    unused_element: error
    unused_local_variable: error
    unused_field: error
    unused_import: error
    unused_type_parameter: error
    dead_code: error
    constant_identifier_names: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_final_fields: error
    prefer_final_locals: error
    prefer_final_parameters: error
    avoid_private_typedef_functions: error
    avoid_relative_lib_imports: error
    avoid_shadowing_type_parameters: error
    avoid_types_as_parameter_names: error
    avoid_unused_constructor_parameters: error
    camel_case_types: error
    camel_case_extensions: error
    camel_case_typedefs: error
    camel_case_variables: error
    camel_case_instance_members: error
    camel_case_constructor_names: error
    camel_case_named_parameters: error
    camel_case_type_variables: error
    camel_case_local_variables: error
    camel_case_parameter_names: error
    camel_case_top_level_function_names: error
    camel_case_constant_names: error
    camel_case_library_prefixes: error
    constant_names: error
    deprecated_mixin: error
    empty_constructor_bodies: error
    empty_statements: error
    hash_and_equals: error
    implementation_imports: error
    invalid_assignment: error
    library_names: error
    library_prefixes: error
    non_constant_identifier_names: error
    null_closures: error
    overridden_fields: error
    overridden_methods: error
    package_api_docs: error
    package_prefixed_library_names: error
    slash_for_doc_comments: error
    super_goes_last: error
    type_init_formals: error
    unnecessary_brace_in_string_interps: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_checks: error
    unnecessary_overrides: error
    unnecessary_this: error
    unnecessary_type_check_false: error
    unnecessary_type_check_true: error
    unnecessary_raw_strings: error
    unnecessary_statements: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_string_to_ints: error
    unnecessary_string_to_double: error
    unnecessary_string_concatenation: error
    unnecessary_type_check: error
    unnecessary_use_of_this: error
    unused_catch_clause: error
    use_rethrow_when_possible: error
    valid_regexps: error
    void_checks: error
    always_declare_return_types: error
    always_require_non_null_named_parameters: error
    always_specify_types: error
    annotate_overrides: error
    avoid_returning_null: error
    avoid_returning_null_for_future: error
    avoid_return_types_on_setters: error
    avoid_types_on_closure_parameters: error
    avoid_void: error
    close_sinks: error
    control_flow_in_finally: error
    empty_catches: error
    invalid_use_of_visible_for_testing_member: error
    missing_return: error
    no_duplicate_case_values: error
    prefer_asserts_in_initializer_lists: error
    prefer_asserts_with_message: error
    prefer_constructors_over_static_methods: error
    prefer_double_quotes: ignore
    prefer_for_elements_to_map_fromIterable: error
    prefer_generic_function_type_aliases: error
