name: fhir_client
description: Dart/Flutter library for consuming FHIR server APIs 
version: 0.0.1-alpha
repository: https://github.com/MelbourneDeveloper/fhir_client

environment:
  sdk: ^3.3.4

dependencies:

dev_dependencies:
  austerity: ^1.2.0
  lints: ^3.0.0
  test: ^1.24.0
