name: fhir_generator
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  jayse: ^0.0.5-beta

dev_dependencies:
  austerity: ^1.2.0
  lints: ^3.0.0
  test: ^1.24.0
